### ISSUE TITLE
Connection Error. Wait 15seconds.

### ISSUE THREAD

**Issue by ftwftw0** [Suyash458/soundcloud-dl#14]
Hello here,

After having struggled for at least one hour installing "pip3" instead of "pip" (which does not work as described in the 'Installation' part in the README.md), I finally managed to install soundcloud-dl and get the 'working' binary in /usr/bin.

Here is my issue: 
_$ sc-dl https://soundcloud.com/tropigwana/gimme-gimme_
Connecting ... 
Connection error. Retrying in 15 seconds.

I tried with different links, as full user profiles (https://soundcloud.com/tropigwana/), tracks (https://soundcloud.com/tropigwana/tracks), albums (https://soundcloud.com/tropigwana/albums), none works.

Any idea ?
Have a good day.
- Florent

**Comment by suyashb95** [comment]
You might be facing installation issues because you have both python 2 and 3 installed? 

Also do you have an API key from SoundCloud? You won't be able to download without that.
