### ISSUE TITLE
Soundcloud apps no longer available; will need a new way to generate tokens

### ISSUE THREAD

**Issue by GiovanH** [Suyash458/soundcloud-dl#15]

**Comment by suyashb95** [comment]
That's true, you can still use the client_id from regular browser sessions though. Check the updated readme

**Comment by rnyPlanet** [comment]
> That's true, you can still use the client_id from regular browser sessions though. Check the updated readme

https://pypi.org/project/soundcloud-lib/  get_credentials() 

in this library you can get the client_id. you can embed it in your library
