### ISSUE TITLE
I'm not sure this works in 2021?

### ISSUE THREAD

**Issue by dataflownow** [Suyash458/soundcloud-dl#21]
I've installed soundcloud-dl and set the API key to a client ID harvested from Chrome dev inspector, but can't get this program to give me anything but errors.  Is anyone currently having success using this project?  TIA

**Comment by suyashb95** [comment]
@baodad could you paste the stack trace here?

**Comment by suyashb95** [comment]
closing since this seems to be fixed in 0.1.25
