### ISSUE TITLE
Command to download uploads only missing 

### ISSUE THREAD

**Issue by oorxx** [Suyash458/soundcloud-dl#27]

**Comment by oorxx** [comment]
I found out that to download the uploads only you had to put the artist profile and no command, i think it might be useful to say it in the --help section in case there's people like me.

**Comment by suyashb95** [comment]
Updated some docs in https://github.com/Suyash458/soundcloud-dl/commit/aaf0632716640d895784aa27d5d3c9d2d9b8e113
